export const processors = [
  {
    "name": "Dimensity 9400 Plus",
    "manufacturer": "MediaTek",
    "performanceScore": 98,
    "performanceGrade": "A+",
    "antutuScore": 2671332,
    "geekbenchSingle": 2927,
    "geekbenchMulti": 9000,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3730,
    "gpu": "Mali-G925 MP12"
  },
  {
    "name": "Snapdragon 8 Elite (Gen 4)",
    "manufacturer": "Qualcomm",
    "performanceScore": 98,
    "performanceGrade": "A+",
    "antutuScore": 2721951,
    "geekbenchSingle": 3155,
    "geekbenchMulti": 9723,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 4320,
    "gpu": "Adreno 830"
  },
  {
    "name": "Apple A19",
    "manufacturer": "Apple",
    "performanceScore": 97,
    "performanceGrade": "A+",
    "antutuScore": 1916678,
    "geekbenchSingle": 3621,
    "geekbenchMulti": 9168,
    "cores": 6,
    "coreConfig": "2+4",
    "clockSpeed": 4260,
    "gpu": "Apple A19 GPU"
  },
  {
    "name": "A19 Pro",
    "manufacturer": "Apple",
    "performanceScore": 98,
    "performanceGrade": "A+",
    "antutuScore": 2427211,
    "geekbenchSingle": 3899,
    "geekbenchMulti": 10021,
    "cores": 6,
    "coreConfig": "2+4",
    "clockSpeed": 4260,
    "gpu": "Apple A19 Pro GPU"
  },
  {
    "name": "A18 Pro",
    "manufacturer": "Apple",
    "performanceScore": 97,
    "performanceGrade": "A+",
    "antutuScore": 1890277,
    "geekbenchSingle": 3582,
    "geekbenchMulti": 9089,
    "cores": 6,
    "coreConfig": "2+4",
    "clockSpeed": 4050,
    "gpu": "Apple A18 Pro GPU"
  },
  {
    "name": "Xring O1",
    "manufacturer": "Xiaomi",
    "performanceScore": 96,
    "performanceGrade": "A+",
    "antutuScore": 2501370,
    "geekbenchSingle": 3086,
    "geekbenchMulti": 9701,
    "cores": 10,
    "coreConfig": "2+4+2+2",
    "clockSpeed": 3900,
    "gpu": "Mali-G925 MP16"
  },
  {
    "name": "Apple A18",
    "manufacturer": "Apple",
    "performanceScore": 95,
    "performanceGrade": "A+",
    "antutuScore": 1622118,
    "geekbenchSingle": 3466,
    "geekbenchMulti": 8592,
    "cores": 6,
    "coreConfig": "2+4",
    "clockSpeed": 4050,
    "gpu": "Apple A18 GPU"
  },
  {
    "name": "Dimensity 9400",
    "manufacturer": "MediaTek",
    "performanceScore": 95,
    "performanceGrade": "A+",
    "antutuScore": 2567604,
    "geekbenchSingle": 2874,
    "geekbenchMulti": 8969,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3620,
    "gpu": "Mali-G925 MP12"
  },
  {
    "name": "Dimensity 9300 Plus",
    "manufacturer": "MediaTek",
    "performanceScore": 94,
    "performanceGrade": "A+",
    "antutuScore": 2094291,
    "geekbenchSingle": 2302,
    "geekbenchMulti": 7547,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3400,
    "gpu": "Mali-G720 MP12"
  },
  {
    "name": "Exynos 2500",
    "manufacturer": "Samsung",
    "performanceScore": 93,
    "performanceGrade": "A+",
    "antutuScore": 2047807,
    "geekbenchSingle": 2522,
    "geekbenchMulti": 9015,
    "cores": 10,
    "coreConfig": "1+2+5+2",
    "clockSpeed": 3300,
    "gpu": "Samsung Xclipse 950"
  },
  {
    "name": "A17 Pro",
    "manufacturer": "Apple",
    "performanceScore": 93,
    "performanceGrade": "A+",
    "antutuScore": 1569382,
    "geekbenchSingle": 2953,
    "geekbenchMulti": 7441,
    "cores": 6,
    "coreConfig": "2+4",
    "clockSpeed": 3780,
    "gpu": "Apple A17 GPU"
  },
  {
    "name": "Snapdragon 8s Gen 4",
    "manufacturer": "Qualcomm",
    "performanceScore": 92,
    "performanceGrade": "A",
    "antutuScore": 2056633,
    "geekbenchSingle": 2154,
    "geekbenchMulti": 6880,
    "cores": 8,
    "coreConfig": "1+3+2+2",
    "clockSpeed": 3210,
    "gpu": "Adreno 825"
  },
  {
    "name": "Dimensity 9300",
    "manufacturer": "MediaTek",
    "performanceScore": 92,
    "performanceGrade": "A",
    "antutuScore": 2070127,
    "geekbenchSingle": 2239,
    "geekbenchMulti": 7538,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3250,
    "gpu": "Mali-G720 MP12"
  },
  {
    "name": "Snapdragon 8 Gen 3",
    "manufacturer": "Qualcomm",
    "performanceScore": 92,
    "performanceGrade": "A",
    "antutuScore": 2050267,
    "geekbenchSingle": 2193,
    "geekbenchMulti": 7304,
    "cores": 8,
    "coreConfig": "1+3+2+2",
    "clockSpeed": 3300,
    "gpu": "Adreno 750"
  },
  {
    "name": "Dimensity 9400e",
    "manufacturer": "MediaTek",
    "performanceScore": 91,
    "performanceGrade": "A",
    "antutuScore": 2128721,
    "geekbenchSingle": 2233,
    "geekbenchMulti": 7258,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3400,
    "gpu": "Mali-G720 MP12"
  },
  {
    "name": "A16 Bionic",
    "manufacturer": "Apple",
    "performanceScore": 89,
    "performanceGrade": "A",
    "antutuScore": 1468347,
    "geekbenchSingle": 2627,
    "geekbenchMulti": 6838,
    "cores": 6,
    "coreConfig": "2+4",
    "clockSpeed": 3460,
    "gpu": "Apple A16 GPU"
  },
  {
    "name": "Exynos 2400",
    "manufacturer": "Samsung",
    "performanceScore": 87,
    "performanceGrade": "A",
    "antutuScore": 1779892,
    "geekbenchSingle": 2196,
    "geekbenchMulti": 6964,
    "cores": 10,
    "coreConfig": "1+2+3+4",
    "clockSpeed": 3210,
    "gpu": "Samsung Xclipse 940"
  },
  {
    "name": "Exynos 2400e",
    "manufacturer": "Samsung",
    "performanceScore": 86,
    "performanceGrade": "A",
    "antutuScore": 1773931,
    "geekbenchSingle": 2099,
    "geekbenchMulti": 6414,
    "cores": 10,
    "coreConfig": "1+2+3+4",
    "clockSpeed": 3110,
    "gpu": "Samsung Xclipse 940"
  },
  {
    "name": "Dimensity 8450",
    "manufacturer": "MediaTek",
    "performanceScore": 83,
    "performanceGrade": "A",
    "antutuScore": 1675507,
    "geekbenchSingle": 1617,
    "geekbenchMulti": 6406,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3250,
    "gpu": "Mali-G720 MP7"
  },
  {
    "name": "Tensor G5",
    "manufacturer": "Google",
    "performanceScore": 83,
    "performanceGrade": "A",
    "antutuScore": 1508196,
    "geekbenchSingle": 2301,
    "geekbenchMulti": 6987,
    "cores": 8,
    "coreConfig": "1+5+2",
    "clockSpeed": 3780,
    "gpu": "PowerVR DXT-48-1536"
  },
  {
    "name": "A15 Bionic",
    "manufacturer": "Apple",
    "performanceScore": 82,
    "performanceGrade": "A",
    "antutuScore": 1319385,
    "geekbenchSingle": 2332,
    "geekbenchMulti": 5736,
    "cores": 6,
    "coreConfig": "2+4",
    "clockSpeed": 3230,
    "gpu": "Apple A15 GPU"
  },
  {
    "name": "Dimensity 8400",
    "manufacturer": "MediaTek",
    "performanceScore": 81,
    "performanceGrade": "A",
    "antutuScore": 1642252,
    "geekbenchSingle": 1571,
    "geekbenchMulti": 6033,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3250,
    "gpu": "Mali-G720 MP7"
  },
  {
    "name": "Snapdragon 8 Gen 2",
    "manufacturer": "Qualcomm",
    "performanceScore": 81,
    "performanceGrade": "A",
    "antutuScore": 1565039,
    "geekbenchSingle": 1991,
    "geekbenchMulti": 5299,
    "cores": 8,
    "coreConfig": "1+2+2+3",
    "clockSpeed": 3200,
    "gpu": "Adreno 740"
  },
  {
    "name": "Dimensity 9200",
    "manufacturer": "MediaTek",
    "performanceScore": 79,
    "performanceGrade": "A",
    "antutuScore": 1468431,
    "geekbenchSingle": 1949,
    "geekbenchMulti": 5281,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3050,
    "gpu": "Mali-G715 MP11"
  },
  {
    "name": "Snapdragon 8s Gen 3",
    "manufacturer": "Qualcomm",
    "performanceScore": 78,
    "performanceGrade": "A",
    "antutuScore": 1479281,
    "geekbenchSingle": 2019,
    "geekbenchMulti": 5570,
    "cores": 8,
    "coreConfig": "1+4+3",
    "clockSpeed": 3000,
    "gpu": "Adreno 735"
  },
  {
    "name": "Dimensity 9200 Plus",
    "manufacturer": "MediaTek",
    "performanceScore": 78,
    "performanceGrade": "A",
    "antutuScore": 1481997,
    "geekbenchSingle": 2090,
    "geekbenchMulti": 5532,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3350,
    "gpu": "Mali-G715 MP11"
  },
  {
    "name": "Snapdragon 7 Plus Gen 3",
    "manufacturer": "Qualcomm",
    "performanceScore": 75,
    "performanceGrade": "A",
    "antutuScore": 1413752,
    "geekbenchSingle": 1913,
    "geekbenchMulti": 5098,
    "cores": 8,
    "coreConfig": "1+4+3",
    "clockSpeed": 2800,
    "gpu": "Adreno 732"
  },
  {
    "name": "Dimensity 8350",
    "manufacturer": "MediaTek",
    "performanceScore": 72,
    "performanceGrade": "A",
    "antutuScore": 1421380,
    "geekbenchSingle": 1285,
    "geekbenchMulti": 4325,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3350,
    "gpu": "Mali-G615 MP6"
  },
  {
    "name": "Tensor G4",
    "manufacturer": "Google",
    "performanceScore": 72,
    "performanceGrade": "A",
    "antutuScore": 1291119,
    "geekbenchSingle": 2005,
    "geekbenchMulti": 4835,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3100,
    "gpu": "Mali-G715 MP7"
  },
  {
    "name": "Dimensity 8300",
    "manufacturer": "MediaTek",
    "performanceScore": 71,
    "performanceGrade": "A",
    "antutuScore": 1405474,
    "geekbenchSingle": 1398,
    "geekbenchMulti": 4293,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3350,
    "gpu": "Mali-G615 MP6"
  },
  {
    "name": "A14 Bionic",
    "manufacturer": "Apple",
    "performanceScore": 71,
    "performanceGrade": "A",
    "antutuScore": 1109899,
    "geekbenchSingle": 2079,
    "geekbenchMulti": 4779,
    "cores": 6,
    "coreConfig": "2+4",
    "clockSpeed": 3100,
    "gpu": "Apple A14 GPU"
  },
  {
    "name": "Snapdragon 8 Plus Gen 1",
    "manufacturer": "Qualcomm",
    "performanceScore": 70,
    "performanceGrade": "A",
    "antutuScore": 1299617,
    "geekbenchSingle": 1767,
    "geekbenchMulti": 4591,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3200,
    "gpu": "Adreno 730"
  },
  {
    "name": "Tensor G3",
    "manufacturer": "Google",
    "performanceScore": 68,
    "performanceGrade": "A",
    "antutuScore": 1151520,
    "geekbenchSingle": 1760,
    "geekbenchMulti": 4442,
    "cores": 9,
    "coreConfig": "1+4+4",
    "clockSpeed": 2910,
    "gpu": "Mali-G715 MP7"
  },
  {
    "name": "Kirin 8020",
    "manufacturer": "HiSilicon",
    "performanceScore": 67,
    "performanceGrade": "A",
    "antutuScore": 1326372,
    "geekbenchSingle": 1350,
    "geekbenchMulti": 3570,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2285,
    "gpu": "Maleoon 920"
  },
  {
    "name": "A13 Bionic",
    "manufacturer": "Apple",
    "performanceScore": 65,
    "performanceGrade": "A",
    "antutuScore": 921243,
    "geekbenchSingle": 1748,
    "geekbenchMulti": 4161,
    "cores": 6,
    "coreConfig": "2+4",
    "clockSpeed": 2650,
    "gpu": "Apple A13 GPU"
  },
  {
    "name": "Dimensity 9000 Plus",
    "manufacturer": "MediaTek",
    "performanceScore": 64,
    "performanceGrade": "B",
    "antutuScore": 1114121,
    "geekbenchSingle": 1647,
    "geekbenchMulti": 4481,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3200,
    "gpu": "Mali-G710 MP10"
  },
  {
    "name": "Snapdragon 8 Gen 1",
    "manufacturer": "Qualcomm",
    "performanceScore": 64,
    "performanceGrade": "B",
    "antutuScore": 1168495,
    "geekbenchSingle": 1661,
    "geekbenchMulti": 4002,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3000,
    "gpu": "Adreno 730"
  },
  {
    "name": "Snapdragon 7 Plus Gen 2",
    "manufacturer": "Qualcomm",
    "performanceScore": 63,
    "performanceGrade": "B",
    "antutuScore": 1124753,
    "geekbenchSingle": 1697,
    "geekbenchMulti": 4404,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2910,
    "gpu": "Adreno 725"
  },
  {
    "name": "Exynos 2200",
    "manufacturer": "Samsung",
    "performanceScore": 63,
    "performanceGrade": "B",
    "antutuScore": 1137188,
    "geekbenchSingle": 1582,
    "geekbenchMulti": 3669,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2800,
    "gpu": "Samsung Xclipse 920"
  },
  {
    "name": "Dimensity 9000",
    "manufacturer": "MediaTek",
    "performanceScore": 62,
    "performanceGrade": "B",
    "antutuScore": 1101116,
    "geekbenchSingle": 1585,
    "geekbenchMulti": 4169,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3050,
    "gpu": "Mali-G710 MP10"
  },
  {
    "name": "Kirin 9020",
    "manufacturer": "HiSilicon",
    "performanceScore": 60,
    "performanceGrade": "B",
    "antutuScore": 1294877,
    "geekbenchSingle": 1298,
    "geekbenchMulti": 4586,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2500,
    "gpu": "Maleoon 920"
  },
  {
    "name": "Snapdragon 7 Gen 4",
    "manufacturer": "Qualcomm",
    "performanceScore": 58,
    "performanceGrade": "B",
    "antutuScore": 1086379,
    "geekbenchSingle": 1204,
    "geekbenchMulti": 3592,
    "cores": 8,
    "coreConfig": "1+4+3",
    "clockSpeed": 2800,
    "gpu": "Adreno 722"
  },
  {
    "name": "Snapdragon 888 Plus",
    "manufacturer": "Qualcomm",
    "performanceScore": 57,
    "performanceGrade": "B",
    "antutuScore": 963578,
    "geekbenchSingle": 1550,
    "geekbenchMulti": 3887,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2995,
    "gpu": "Adreno 660"
  },
  {
    "name": "Snapdragon 888",
    "manufacturer": "Qualcomm",
    "performanceScore": 56,
    "performanceGrade": "B",
    "antutuScore": 919201,
    "geekbenchSingle": 1427,
    "geekbenchMulti": 3423,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2840,
    "gpu": "Adreno 660"
  },
  {
    "name": "Dimensity 8200",
    "manufacturer": "MediaTek",
    "performanceScore": 55,
    "performanceGrade": "B",
    "antutuScore": 936624,
    "geekbenchSingle": 1224,
    "geekbenchMulti": 3891,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3100,
    "gpu": "Mali-G610 MP6"
  },
  {
    "name": "Tensor G2",
    "manufacturer": "Google",
    "performanceScore": 55,
    "performanceGrade": "B",
    "antutuScore": 938380,
    "geekbenchSingle": 1439,
    "geekbenchMulti": 3802,
    "cores": 8,
    "coreConfig": "2+2+4",
    "clockSpeed": 2850,
    "gpu": "Mali-G710 MP7"
  },
  {
    "name": "Exynos 1580",
    "manufacturer": "Samsung",
    "performanceScore": 54,
    "performanceGrade": "B",
    "antutuScore": 910406,
    "geekbenchSingle": 1360,
    "geekbenchMulti": 3893,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2900,
    "gpu": "Samsung Xclipse 540"
  },
  {
    "name": "Google Tensor",
    "manufacturer": "Google",
    "performanceScore": 54,
    "performanceGrade": "B",
    "antutuScore": 897676,
    "geekbenchSingle": 1317,
    "geekbenchMulti": 3208,
    "cores": 8,
    "coreConfig": "2+2+4",
    "clockSpeed": 2800,
    "gpu": "Mali-G78 MP20"
  },
  {
    "name": "Snapdragon 7s Gen 4",
    "manufacturer": "Qualcomm",
    "performanceScore": 53,
    "performanceGrade": "B",
    "antutuScore": 854884,
    "geekbenchSingle": 1214,
    "geekbenchMulti": 3314,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2700,
    "gpu": "Adreno 810"
  },
  {
    "name": "Exynos 2100",
    "manufacturer": "Samsung",
    "performanceScore": 53,
    "performanceGrade": "B",
    "antutuScore": 894668,
    "geekbenchSingle": 1356,
    "geekbenchMulti": 3348,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2900,
    "gpu": "Mali-G78 MP14"
  },
  {
    "name": "Kirin 9000",
    "manufacturer": "HiSilicon",
    "performanceScore": 53,
    "performanceGrade": "B",
    "antutuScore": 901517,
    "geekbenchSingle": 1262,
    "geekbenchMulti": 3507,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3130,
    "gpu": "Mali-G78 MP24"
  },
  {
    "name": "Kirin 9010",
    "manufacturer": "HiSilicon",
    "performanceScore": 52,
    "performanceGrade": "B",
    "antutuScore": 956941,
    "geekbenchSingle": 1410,
    "geekbenchMulti": 4176,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2300,
    "gpu": "Maleoon 910"
  },
  {
    "name": "Dimensity 8100",
    "manufacturer": "MediaTek",
    "performanceScore": 52,
    "performanceGrade": "B",
    "antutuScore": 855531,
    "geekbenchSingle": 1140,
    "geekbenchMulti": 3624,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2850,
    "gpu": "Mali-G610 MP6"
  },
  {
    "name": "Snapdragon 7s Gen 3",
    "manufacturer": "Qualcomm",
    "performanceScore": 50,
    "performanceGrade": "B",
    "antutuScore": 807253,
    "geekbenchSingle": 1178,
    "geekbenchMulti": 3146,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2500,
    "gpu": "Adreno 810"
  },
  {
    "name": "Snapdragon 7 Gen 3",
    "manufacturer": "Qualcomm",
    "performanceScore": 50,
    "performanceGrade": "B",
    "antutuScore": 818589,
    "geekbenchSingle": 1139,
    "geekbenchMulti": 3375,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2630,
    "gpu": "Adreno 720"
  },
  {
    "name": "A12 Bionic",
    "manufacturer": "Apple",
    "performanceScore": 50,
    "performanceGrade": "B",
    "antutuScore": 706955,
    "geekbenchSingle": 1292,
    "geekbenchMulti": 2837,
    "cores": 6,
    "coreConfig": "2+4",
    "clockSpeed": 2490,
    "gpu": "Apple A12 GPU"
  },
  {
    "name": "Dimensity 8000",
    "manufacturer": "MediaTek",
    "performanceScore": 49,
    "performanceGrade": "B",
    "antutuScore": 863025,
    "geekbenchSingle": 1112,
    "geekbenchMulti": 3498,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2750,
    "gpu": "Mali-G610 MP6"
  },
  {
    "name": "Snapdragon 870",
    "manufacturer": "Qualcomm",
    "performanceScore": 49,
    "performanceGrade": "B",
    "antutuScore": 819641,
    "geekbenchSingle": 1141,
    "geekbenchMulti": 3317,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3200,
    "gpu": "Adreno 650"
  },
  {
    "name": "Snapdragon 6 Gen 4",
    "manufacturer": "Qualcomm",
    "performanceScore": 48,
    "performanceGrade": "B",
    "antutuScore": 759266,
    "geekbenchSingle": 1091,
    "geekbenchMulti": 3085,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2300,
    "gpu": "Adreno 810"
  },
  {
    "name": "Dimensity 7350",
    "manufacturer": "MediaTek",
    "performanceScore": 48,
    "performanceGrade": "B",
    "antutuScore": 753533,
    "geekbenchSingle": 1086,
    "geekbenchMulti": 3063,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 3000,
    "gpu": "Mali-G610 MP4"
  },
  {
    "name": "Dimensity 8050",
    "manufacturer": "MediaTek",
    "performanceScore": 48,
    "performanceGrade": "B",
    "antutuScore": 767039,
    "geekbenchSingle": 1097,
    "geekbenchMulti": 3359,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3000,
    "gpu": "Mali-G77 MP9"
  },
  {
    "name": "Dimensity 1300",
    "manufacturer": "MediaTek",
    "performanceScore": 48,
    "performanceGrade": "B",
    "antutuScore": 748318,
    "geekbenchSingle": 1242,
    "geekbenchMulti": 3444,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3000,
    "gpu": "Mali-G77 MP9"
  },
  {
    "name": "Snapdragon 865 Plus",
    "manufacturer": "Qualcomm",
    "performanceScore": 48,
    "performanceGrade": "B",
    "antutuScore": 737495,
    "geekbenchSingle": 1162,
    "geekbenchMulti": 3276,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3100,
    "gpu": "Adreno 650"
  },
  {
    "name": "Kirin 9000S",
    "manufacturer": "HiSilicon",
    "performanceScore": 47,
    "performanceGrade": "B",
    "antutuScore": 823241,
    "geekbenchSingle": 1324,
    "geekbenchMulti": 4116,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2620,
    "gpu": "Maleoon 910"
  },
  {
    "name": "Dimensity 8020",
    "manufacturer": "MediaTek",
    "performanceScore": 47,
    "performanceGrade": "B",
    "antutuScore": 747153,
    "geekbenchSingle": 1122,
    "geekbenchMulti": 3681,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2600,
    "gpu": "Mali-G77 MP9"
  },
  {
    "name": "Dimensity 1200",
    "manufacturer": "MediaTek",
    "performanceScore": 47,
    "performanceGrade": "B",
    "antutuScore": 759514,
    "geekbenchSingle": 1113,
    "geekbenchMulti": 3172,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 3000,
    "gpu": "Mali-G77 MP9"
  },
  {
    "name": "Snapdragon 865",
    "manufacturer": "Qualcomm",
    "performanceScore": 47,
    "performanceGrade": "B",
    "antutuScore": 759272,
    "geekbenchSingle": 1117,
    "geekbenchMulti": 3274,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2840,
    "gpu": "Adreno 650"
  },
  {
    "name": "Dimensity 7200 Ultra",
    "manufacturer": "MediaTek",
    "performanceScore": 46,
    "performanceGrade": "B",
    "antutuScore": 754073,
    "geekbenchSingle": 1128,
    "geekbenchMulti": 2710,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2800,
    "gpu": "Mali-G610 MP4"
  },
  {
    "name": "Dimensity 7200",
    "manufacturer": "MediaTek",
    "performanceScore": 46,
    "performanceGrade": "B",
    "antutuScore": 720423,
    "geekbenchSingle": 1187,
    "geekbenchMulti": 2643,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2800,
    "gpu": "Mali-G610 MP4"
  },
  {
    "name": "Dimensity 1100",
    "manufacturer": "MediaTek",
    "performanceScore": 46,
    "performanceGrade": "B",
    "antutuScore": 748430,
    "geekbenchSingle": 1104,
    "geekbenchMulti": 3321,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2600,
    "gpu": "Mali-G77 MP9"
  },
  {
    "name": "Dimensity 7400",
    "manufacturer": "MediaTek",
    "performanceScore": 45,
    "performanceGrade": "B",
    "antutuScore": 745001,
    "geekbenchSingle": 1033,
    "geekbenchMulti": 2949,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2600,
    "gpu": "Mali-G615 MP2"
  },
  {
    "name": "Exynos 1480",
    "manufacturer": "Samsung",
    "performanceScore": 45,
    "performanceGrade": "B",
    "antutuScore": 720015,
    "geekbenchSingle": 1168,
    "geekbenchMulti": 3503,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2750,
    "gpu": "Samsung Xclipse 530"
  },
  {
    "name": "Dimensity 7300",
    "manufacturer": "MediaTek",
    "performanceScore": 44,
    "performanceGrade": "B",
    "antutuScore": 668790,
    "geekbenchSingle": 1058,
    "geekbenchMulti": 3025,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2500,
    "gpu": "Mali-G615 MP2"
  },
  {
    "name": "Snapdragon 782G",
    "manufacturer": "Qualcomm",
    "performanceScore": 44,
    "performanceGrade": "B",
    "antutuScore": 682050,
    "geekbenchSingle": 1119,
    "geekbenchMulti": 2820,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2700,
    "gpu": "Adreno 642"
  },
  {
    "name": "Snapdragon 7 Gen 1",
    "manufacturer": "Qualcomm",
    "performanceScore": 44,
    "performanceGrade": "B",
    "antutuScore": 678813,
    "geekbenchSingle": 964,
    "geekbenchMulti": 2761,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2400,
    "gpu": "Adreno 644"
  },
  {
    "name": "Exynos 990",
    "manufacturer": "Samsung",
    "performanceScore": 44,
    "performanceGrade": "B",
    "antutuScore": 742810,
    "geekbenchSingle": 840,
    "geekbenchMulti": 2670,
    "cores": 8,
    "coreConfig": "2+2+4",
    "clockSpeed": 2730,
    "gpu": "Mali-G77 MP11"
  },
  {
    "name": "Kirin 990 (5G)",
    "manufacturer": "HiSilicon",
    "performanceScore": 44,
    "performanceGrade": "B",
    "antutuScore": 714339,
    "geekbenchSingle": 964,
    "geekbenchMulti": 3146,
    "cores": 8,
    "coreConfig": "2+2+4",
    "clockSpeed": 2860,
    "gpu": "Mali-G76 MP16"
  },
  {
    "name": "Snapdragon 6 Gen 3",
    "manufacturer": "Qualcomm",
    "performanceScore": 43,
    "performanceGrade": "B",
    "antutuScore": 626377,
    "geekbenchSingle": 1017,
    "geekbenchMulti": 2910,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2400,
    "gpu": "Adreno 710"
  },
  {
    "name": "Snapdragon 778G Plus",
    "manufacturer": "Qualcomm",
    "performanceScore": 43,
    "performanceGrade": "B",
    "antutuScore": 634727,
    "geekbenchSingle": 1064,
    "geekbenchMulti": 3006,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2500,
    "gpu": "Adreno 642"
  },
  {
    "name": "Snapdragon 780G",
    "manufacturer": "Qualcomm",
    "performanceScore": 43,
    "performanceGrade": "B",
    "antutuScore": 633483,
    "geekbenchSingle": 1040,
    "geekbenchMulti": 2743,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2400,
    "gpu": "Adreno 642"
  },
  {
    "name": "Snapdragon 860",
    "manufacturer": "Qualcomm",
    "performanceScore": 43,
    "performanceGrade": "B",
    "antutuScore": 642297,
    "geekbenchSingle": 988,
    "geekbenchMulti": 2560,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2960,
    "gpu": "Adreno 640"
  },
  {
    "name": "Dimensity 1000 Plus",
    "manufacturer": "MediaTek",
    "performanceScore": 43,
    "performanceGrade": "B",
    "antutuScore": 582561,
    "geekbenchSingle": 1031,
    "geekbenchMulti": 3123,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2600,
    "gpu": "Mali-G77 MP9"
  },
  {
    "name": "Snapdragon 855 Plus",
    "manufacturer": "Qualcomm",
    "performanceScore": 43,
    "performanceGrade": "B",
    "antutuScore": 617502,
    "geekbenchSingle": 1031,
    "geekbenchMulti": 2864,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2960,
    "gpu": "Adreno 640"
  },
  {
    "name": "Snapdragon 855",
    "manufacturer": "Qualcomm",
    "performanceScore": 43,
    "performanceGrade": "B",
    "antutuScore": 616110,
    "geekbenchSingle": 930,
    "geekbenchMulti": 2834,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2840,
    "gpu": "Adreno 640"
  },
  {
    "name": "Snapdragon 7s Gen 2",
    "manufacturer": "Qualcomm",
    "performanceScore": 42,
    "performanceGrade": "B",
    "antutuScore": 609384,
    "geekbenchSingle": 1012,
    "geekbenchMulti": 2943,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2400,
    "gpu": "Adreno 710"
  },
  {
    "name": "Snapdragon 778G",
    "manufacturer": "Qualcomm",
    "performanceScore": 42,
    "performanceGrade": "B",
    "antutuScore": 597831,
    "geekbenchSingle": 1017,
    "geekbenchMulti": 2841,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2400,
    "gpu": "Adreno 642"
  },
  {
    "name": "Kirin 8000",
    "manufacturer": "HiSilicon",
    "performanceScore": 40,
    "performanceGrade": "B",
    "antutuScore": 624267,
    "geekbenchSingle": 999,
    "geekbenchMulti": 2948,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2400,
    "gpu": "Mali-G610 MP4"
  },
  {
    "name": "Dimensity 7030",
    "manufacturer": "MediaTek",
    "performanceScore": 40,
    "performanceGrade": "B",
    "antutuScore": 540999,
    "geekbenchSingle": 1024,
    "geekbenchMulti": 2412,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2500,
    "gpu": "Mali-G610 MP3"
  },
  {
    "name": "Snapdragon 6 Gen 1",
    "manufacturer": "Qualcomm",
    "performanceScore": 40,
    "performanceGrade": "B",
    "antutuScore": 563430,
    "geekbenchSingle": 943,
    "geekbenchMulti": 2748,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2200,
    "gpu": "Adreno 710"
  },
  {
    "name": "Dimensity 1080",
    "manufacturer": "MediaTek",
    "performanceScore": 40,
    "performanceGrade": "B",
    "antutuScore": 548612,
    "geekbenchSingle": 965,
    "geekbenchMulti": 2409,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2600,
    "gpu": "Mali-G68 MP4"
  },
  {
    "name": "Exynos 9825",
    "manufacturer": "Samsung",
    "performanceScore": 40,
    "performanceGrade": "B",
    "antutuScore": 667934,
    "geekbenchSingle": 669,
    "geekbenchMulti": 2354,
    "cores": 8,
    "coreConfig": "2+2+4",
    "clockSpeed": 2730,
    "gpu": "Mali-G76 MP12"
  },
  {
    "name": "A11 Bionic",
    "manufacturer": "Apple",
    "performanceScore": 40,
    "performanceGrade": "B",
    "antutuScore": 497740,
    "geekbenchSingle": 1087,
    "geekbenchMulti": 2346,
    "cores": 6,
    "coreConfig": "2+4",
    "clockSpeed": 2390,
    "gpu": "Apple A11 GPU"
  },
  {
    "name": "Dimensity 7050",
    "manufacturer": "MediaTek",
    "performanceScore": 39,
    "performanceGrade": "B",
    "antutuScore": 595924,
    "geekbenchSingle": 956,
    "geekbenchMulti": 2343,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2600,
    "gpu": "Mali-G68 MP4"
  },
  {
    "name": "Exynos 1380",
    "manufacturer": "Samsung",
    "performanceScore": 39,
    "performanceGrade": "B",
    "antutuScore": 597714,
    "geekbenchSingle": 999,
    "geekbenchMulti": 2758,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2400,
    "gpu": "Mali-G68 MP5"
  },
  {
    "name": "Dimensity 920",
    "manufacturer": "MediaTek",
    "performanceScore": 39,
    "performanceGrade": "B",
    "antutuScore": 548039,
    "geekbenchSingle": 926,
    "geekbenchMulti": 2310,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2500,
    "gpu": "Mali-G68 MP4"
  },
  {
    "name": "Exynos 9820",
    "manufacturer": "Samsung",
    "performanceScore": 39,
    "performanceGrade": "B",
    "antutuScore": 624243,
    "geekbenchSingle": 741,
    "geekbenchMulti": 2317,
    "cores": 8,
    "coreConfig": "2+2+4",
    "clockSpeed": 2730,
    "gpu": "Mali-G76 MP12"
  },
  {
    "name": "Dimensity 930",
    "manufacturer": "MediaTek",
    "performanceScore": 38,
    "performanceGrade": "B",
    "antutuScore": 462254,
    "geekbenchSingle": 920,
    "geekbenchMulti": 2325,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "IMG BXM-8-256"
  },
  {
    "name": "Kirin 980",
    "manufacturer": "HiSilicon",
    "performanceScore": 38,
    "performanceGrade": "B",
    "antutuScore": 591752,
    "geekbenchSingle": 834,
    "geekbenchMulti": 2128,
    "cores": 8,
    "coreConfig": "2+2+4",
    "clockSpeed": 2600,
    "gpu": "Mali-G76 MP10"
  },
  {
    "name": "Dimensity 6400",
    "manufacturer": "MediaTek",
    "performanceScore": 37,
    "performanceGrade": "B",
    "antutuScore": 500600,
    "geekbenchSingle": 803,
    "geekbenchMulti": 2159,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2500,
    "gpu": "Mali-G57 MP2"
  },
  {
    "name": "Snapdragon 6s Gen 3",
    "manufacturer": "Qualcomm",
    "performanceScore": 37,
    "performanceGrade": "B",
    "antutuScore": 453329,
    "geekbenchSingle": 940,
    "geekbenchMulti": 2115,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2300,
    "gpu": "Adreno 619"
  },
  {
    "name": "Dimensity 1050",
    "manufacturer": "MediaTek",
    "performanceScore": 37,
    "performanceGrade": "B",
    "antutuScore": 527778,
    "geekbenchSingle": 986,
    "geekbenchMulti": 2432,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2500,
    "gpu": "Mali-G610 MP3"
  },
  {
    "name": "Dimensity 820",
    "manufacturer": "MediaTek",
    "performanceScore": 37,
    "performanceGrade": "B",
    "antutuScore": 487164,
    "geekbenchSingle": 845,
    "geekbenchMulti": 2484,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2600,
    "gpu": "Mali-G57 MP5"
  },
  {
    "name": "Kirin 820",
    "manufacturer": "HiSilicon",
    "performanceScore": 37,
    "performanceGrade": "B",
    "antutuScore": 494513,
    "geekbenchSingle": 788,
    "geekbenchMulti": 1972,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2360,
    "gpu": "Mali-G57 MP6"
  },
  {
    "name": "Dimensity 7060",
    "manufacturer": "MediaTek",
    "performanceScore": 36,
    "performanceGrade": "B",
    "antutuScore": 424633,
    "geekbenchSingle": 1009,
    "geekbenchMulti": 2413,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2600,
    "gpu": "IMG BXM-8-256"
  },
  {
    "name": "Unisoc T9100",
    "manufacturer": "Unisoc",
    "performanceScore": 36,
    "performanceGrade": "B",
    "antutuScore": 522667,
    "geekbenchSingle": 891,
    "geekbenchMulti": 2445,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2700,
    "gpu": "Mali-G57 MP4"
  },
  {
    "name": "Dimensity 7025",
    "manufacturer": "MediaTek",
    "performanceScore": 36,
    "performanceGrade": "B",
    "antutuScore": 459847,
    "geekbenchSingle": 1024,
    "geekbenchMulti": 2472,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2500,
    "gpu": "IMG BXM-8-256"
  },
  {
    "name": "Unisoc T820",
    "manufacturer": "Unisoc",
    "performanceScore": 36,
    "performanceGrade": "B",
    "antutuScore": 544716,
    "geekbenchSingle": 888,
    "geekbenchMulti": 2433,
    "cores": 8,
    "coreConfig": "1+3+4",
    "clockSpeed": 2700,
    "gpu": "Mali-G57 MP4"
  },
  {
    "name": "Snapdragon 4 Gen 2",
    "manufacturer": "Qualcomm",
    "performanceScore": 36,
    "performanceGrade": "B",
    "antutuScore": 427069,
    "geekbenchSingle": 918,
    "geekbenchMulti": 2121,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Adreno 613"
  },
  {
    "name": "Dimensity 900",
    "manufacturer": "MediaTek",
    "performanceScore": 36,
    "performanceGrade": "B",
    "antutuScore": 515609,
    "geekbenchSingle": 898,
    "geekbenchMulti": 2239,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2400,
    "gpu": "Mali-G68 MP4"
  },
  {
    "name": "Helio G200",
    "manufacturer": "MediaTek",
    "performanceScore": 35,
    "performanceGrade": "B",
    "antutuScore": 460004,
    "geekbenchSingle": 738,
    "geekbenchMulti": 2011,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Mali-G57 MP2"
  },
  {
    "name": "Unisoc T8300",
    "manufacturer": "Unisoc",
    "performanceScore": 35,
    "performanceGrade": "B",
    "antutuScore": 479599,
    "geekbenchSingle": 752,
    "geekbenchMulti": 2209,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Mali-G57 MP2"
  },
  {
    "name": "Dimensity 6300",
    "manufacturer": "MediaTek",
    "performanceScore": 35,
    "performanceGrade": "B",
    "antutuScore": 425577,
    "geekbenchSingle": 782,
    "geekbenchMulti": 2012,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2400,
    "gpu": "Mali-G57 MP2"
  },
  {
    "name": "Dimensity 7020",
    "manufacturer": "MediaTek",
    "performanceScore": 35,
    "performanceGrade": "B",
    "antutuScore": 461937,
    "geekbenchSingle": 884,
    "geekbenchMulti": 2291,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "IMG BXM-8-256"
  },
  {
    "name": "Snapdragon 695",
    "manufacturer": "Qualcomm",
    "performanceScore": 35,
    "performanceGrade": "B",
    "antutuScore": 442196,
    "geekbenchSingle": 908,
    "geekbenchMulti": 2134,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Adreno 619"
  },
  {
    "name": "Snapdragon 765G",
    "manufacturer": "Qualcomm",
    "performanceScore": 35,
    "performanceGrade": "B",
    "antutuScore": 437036,
    "geekbenchSingle": 797,
    "geekbenchMulti": 1844,
    "cores": 8,
    "coreConfig": "1+1+6",
    "clockSpeed": 2400,
    "gpu": "Adreno 620"
  },
  {
    "name": "Snapdragon 845",
    "manufacturer": "Qualcomm",
    "performanceScore": 35,
    "performanceGrade": "B",
    "antutuScore": 463819,
    "geekbenchSingle": 564,
    "geekbenchMulti": 2074,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2800,
    "gpu": "Adreno 630"
  },
  {
    "name": "Helio G100",
    "manufacturer": "MediaTek",
    "performanceScore": 34,
    "performanceGrade": "C",
    "antutuScore": 430430,
    "geekbenchSingle": 733,
    "geekbenchMulti": 2028,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Mali-G57 MP2"
  },
  {
    "name": "Snapdragon 4s Gen 2",
    "manufacturer": "Qualcomm",
    "performanceScore": 34,
    "performanceGrade": "C",
    "antutuScore": 376951,
    "geekbenchSingle": 838,
    "geekbenchMulti": 1899,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Adreno 611"
  },
  {
    "name": "Unisoc T760",
    "manufacturer": "Unisoc",
    "performanceScore": 34,
    "performanceGrade": "C",
    "antutuScore": 472470,
    "geekbenchSingle": 744,
    "geekbenchMulti": 2390,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2200,
    "gpu": "Mali-G57 MP4"
  },
  {
    "name": "Dimensity 6080",
    "manufacturer": "MediaTek",
    "performanceScore": 34,
    "performanceGrade": "C",
    "antutuScore": 435520,
    "geekbenchSingle": 767,
    "geekbenchMulti": 2057,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2400,
    "gpu": "Mali-G57 MP2"
  },
  {
    "name": "Exynos 1330",
    "manufacturer": "Samsung",
    "performanceScore": 34,
    "performanceGrade": "C",
    "antutuScore": 438848,
    "geekbenchSingle": 929,
    "geekbenchMulti": 2128,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2400,
    "gpu": "Mali-G68 MP2"
  },
  {
    "name": "Snapdragon 4 Gen 1",
    "manufacturer": "Qualcomm",
    "performanceScore": 34,
    "performanceGrade": "C",
    "antutuScore": 416776,
    "geekbenchSingle": 837,
    "geekbenchMulti": 1875,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Adreno 619"
  },
  {
    "name": "Exynos 1280",
    "manufacturer": "Samsung",
    "performanceScore": 34,
    "performanceGrade": "C",
    "antutuScore": 478526,
    "geekbenchSingle": 851,
    "geekbenchMulti": 1913,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2400,
    "gpu": "Mali-G68 MP4"
  },
  {
    "name": "Dimensity 810",
    "manufacturer": "MediaTek",
    "performanceScore": 34,
    "performanceGrade": "C",
    "antutuScore": 421890,
    "geekbenchSingle": 780,
    "geekbenchMulti": 1940,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2400,
    "gpu": "Mali-G57 MP2"
  },
  {
    "name": "Snapdragon 750G",
    "manufacturer": "Qualcomm",
    "performanceScore": 34,
    "performanceGrade": "C",
    "antutuScore": 396590,
    "geekbenchSingle": 875,
    "geekbenchMulti": 2095,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Adreno 619"
  },
  {
    "name": "Snapdragon 732G",
    "manufacturer": "Qualcomm",
    "performanceScore": 34,
    "performanceGrade": "C",
    "antutuScore": 398133,
    "geekbenchSingle": 747,
    "geekbenchMulti": 1843,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2300,
    "gpu": "Adreno 618"
  },
  {
    "name": "Dimensity 800",
    "manufacturer": "MediaTek",
    "performanceScore": 34,
    "performanceGrade": "C",
    "antutuScore": 481286,
    "geekbenchSingle": 638,
    "geekbenchMulti": 2255,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2000,
    "gpu": "Mali-G57 MP4"
  },
  {
    "name": "Exynos 980",
    "manufacturer": "Samsung",
    "performanceScore": 34,
    "performanceGrade": "C",
    "antutuScore": 467073,
    "geekbenchSingle": 861,
    "geekbenchMulti": 1858,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Mali-G76 MP5"
  },
  {
    "name": "Dimensity 6100 Plus",
    "manufacturer": "MediaTek",
    "performanceScore": 33,
    "performanceGrade": "C",
    "antutuScore": 392866,
    "geekbenchSingle": 728,
    "geekbenchMulti": 1938,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Mali-G57 MP2"
  },
  {
    "name": "Dimensity 6020",
    "manufacturer": "MediaTek",
    "performanceScore": 33,
    "performanceGrade": "C",
    "antutuScore": 404064,
    "geekbenchSingle": 732,
    "geekbenchMulti": 1924,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Mali-G57 MP2"
  },
  {
    "name": "Helio G99",
    "manufacturer": "MediaTek",
    "performanceScore": 33,
    "performanceGrade": "C",
    "antutuScore": 422461,
    "geekbenchSingle": 729,
    "geekbenchMulti": 1979,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Mali-G57 MP2"
  },
  {
    "name": "Snapdragon 480 Plus",
    "manufacturer": "Qualcomm",
    "performanceScore": 33,
    "performanceGrade": "C",
    "antutuScore": 390749,
    "geekbenchSingle": 862,
    "geekbenchMulti": 1857,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Adreno 619"
  },
  {
    "name": "Dimensity 800U",
    "manufacturer": "MediaTek",
    "performanceScore": 33,
    "performanceGrade": "C",
    "antutuScore": 433106,
    "geekbenchSingle": 752,
    "geekbenchMulti": 1836,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2400,
    "gpu": "Mali-G57 MP3"
  },
  {
    "name": "Snapdragon 720G",
    "manufacturer": "Qualcomm",
    "performanceScore": 33,
    "performanceGrade": "C",
    "antutuScore": 389059,
    "geekbenchSingle": 750,
    "geekbenchMulti": 1774,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2300,
    "gpu": "Adreno 618"
  },
  {
    "name": "Kirin 810",
    "manufacturer": "HiSilicon",
    "performanceScore": 33,
    "performanceGrade": "C",
    "antutuScore": 431674,
    "geekbenchSingle": 770,
    "geekbenchMulti": 1983,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2270,
    "gpu": "Mali-G52 MP6"
  },
  {
    "name": "Snapdragon 480",
    "manufacturer": "Qualcomm",
    "performanceScore": 32,
    "performanceGrade": "C",
    "antutuScore": 356931,
    "geekbenchSingle": 693,
    "geekbenchMulti": 1802,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Adreno 619"
  },
  {
    "name": "Dimensity 700",
    "manufacturer": "MediaTek",
    "performanceScore": 32,
    "performanceGrade": "C",
    "antutuScore": 382741,
    "geekbenchSingle": 711,
    "geekbenchMulti": 1783,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Mali-G57 MP2"
  },
  {
    "name": "Dimensity 720",
    "manufacturer": "MediaTek",
    "performanceScore": 32,
    "performanceGrade": "C",
    "antutuScore": 388163,
    "geekbenchSingle": 770,
    "geekbenchMulti": 1844,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Mali-G57 MP3"
  },
  {
    "name": "Snapdragon 690",
    "manufacturer": "Qualcomm",
    "performanceScore": 32,
    "performanceGrade": "C",
    "antutuScore": 382798,
    "geekbenchSingle": 792,
    "geekbenchMulti": 1889,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Adreno 619"
  },
  {
    "name": "Snapdragon 730G",
    "manufacturer": "Qualcomm",
    "performanceScore": 32,
    "performanceGrade": "C",
    "antutuScore": 377951,
    "geekbenchSingle": 697,
    "geekbenchMulti": 1809,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Adreno 618"
  },
  {
    "name": "Exynos 9810",
    "manufacturer": "Samsung",
    "performanceScore": 32,
    "performanceGrade": "C",
    "antutuScore": 467429,
    "geekbenchSingle": 559,
    "geekbenchMulti": 1840,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2900,
    "gpu": "Mali-G72 MP18"
  },
  {
    "name": "Snapdragon 685",
    "manufacturer": "Qualcomm",
    "performanceScore": 31,
    "performanceGrade": "C",
    "antutuScore": 348982,
    "geekbenchSingle": 473,
    "geekbenchMulti": 1510,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2800,
    "gpu": "Adreno 610"
  },
  {
    "name": "Helio G95",
    "manufacturer": "MediaTek",
    "performanceScore": 31,
    "performanceGrade": "C",
    "antutuScore": 409383,
    "geekbenchSingle": 636,
    "geekbenchMulti": 1738,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2050,
    "gpu": "Mali-G76 MP4"
  },
  {
    "name": "Snapdragon 730",
    "manufacturer": "Qualcomm",
    "performanceScore": 31,
    "performanceGrade": "C",
    "antutuScore": 357235,
    "geekbenchSingle": 691,
    "geekbenchMulti": 1629,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Adreno 618"
  },
  {
    "name": "Helio G96",
    "manufacturer": "MediaTek",
    "performanceScore": 30,
    "performanceGrade": "C",
    "antutuScore": 380990,
    "geekbenchSingle": 645,
    "geekbenchMulti": 1855,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2050,
    "gpu": "Mali-G57 MP2"
  },
  {
    "name": "Helio G90",
    "manufacturer": "MediaTek",
    "performanceScore": 30,
    "performanceGrade": "C",
    "antutuScore": 368990,
    "geekbenchSingle": 625,
    "geekbenchMulti": 1744,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2050,
    "gpu": "Mali-G76 MP4"
  },
  {
    "name": "Helio G90T",
    "manufacturer": "MediaTek",
    "performanceScore": 30,
    "performanceGrade": "C",
    "antutuScore": 368990,
    "geekbenchSingle": 649,
    "geekbenchMulti": 1835,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2050,
    "gpu": "Mali-G76 MP4"
  },
  {
    "name": "A10 Fusion",
    "manufacturer": "Apple",
    "performanceScore": 30,
    "performanceGrade": "C",
    "antutuScore": 398082,
    "geekbenchSingle": 878,
    "geekbenchMulti": 1319,
    "cores": 4,
    "coreConfig": "2+2",
    "clockSpeed": 2340,
    "gpu": "PowerVR GT7600"
  },
  {
    "name": "Snapdragon 680",
    "manufacturer": "Qualcomm",
    "performanceScore": 29,
    "performanceGrade": "C",
    "antutuScore": 308333,
    "geekbenchSingle": 412,
    "geekbenchMulti": 1444,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2400,
    "gpu": "Adreno 610"
  },
  {
    "name": "Snapdragon 678",
    "manufacturer": "Qualcomm",
    "performanceScore": 29,
    "performanceGrade": "C",
    "antutuScore": 337557,
    "geekbenchSingle": 680,
    "geekbenchMulti": 1556,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Adreno 612"
  },
  {
    "name": "Snapdragon 835",
    "manufacturer": "Qualcomm",
    "performanceScore": 29,
    "performanceGrade": "C",
    "antutuScore": 368607,
    "geekbenchSingle": 415,
    "geekbenchMulti": 1508,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2450,
    "gpu": "Adreno 540"
  },
  {
    "name": "Snapdragon 712",
    "manufacturer": "Qualcomm",
    "performanceScore": 28,
    "performanceGrade": "C",
    "antutuScore": 311741,
    "geekbenchSingle": 446,
    "geekbenchMulti": 1436,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2300,
    "gpu": "Adreno 616"
  },
  {
    "name": "Snapdragon 675",
    "manufacturer": "Qualcomm",
    "performanceScore": 28,
    "performanceGrade": "C",
    "antutuScore": 314867,
    "geekbenchSingle": 671,
    "geekbenchMulti": 1695,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Adreno 612"
  },
  {
    "name": "Kirin 970",
    "manufacturer": "HiSilicon",
    "performanceScore": 28,
    "performanceGrade": "C",
    "antutuScore": 372441,
    "geekbenchSingle": 383,
    "geekbenchMulti": 1373,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2360,
    "gpu": "Mali-G72 MP12"
  },
  {
    "name": "Exynos 8895",
    "manufacturer": "Samsung",
    "performanceScore": 28,
    "performanceGrade": "C",
    "antutuScore": 372105,
    "geekbenchSingle": 418,
    "geekbenchMulti": 1429,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2314,
    "gpu": "Mali-G71 MP20"
  },
  {
    "name": "Tiger T620",
    "manufacturer": "Unisoc",
    "performanceScore": 27,
    "performanceGrade": "C",
    "antutuScore": 332915,
    "geekbenchSingle": 497,
    "geekbenchMulti": 1541,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Mali-G57 MP1"
  },
  {
    "name": "Helio P95",
    "manufacturer": "MediaTek",
    "performanceScore": 27,
    "performanceGrade": "C",
    "antutuScore": 299534,
    "geekbenchSingle": 456,
    "geekbenchMulti": 1541,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "PowerVR GM9446"
  },
  {
    "name": "Snapdragon 710",
    "manufacturer": "Qualcomm",
    "performanceScore": 27,
    "performanceGrade": "C",
    "antutuScore": 298526,
    "geekbenchSingle": 445,
    "geekbenchMulti": 1352,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "Adreno 616"
  },
  {
    "name": "Helio G92 Max",
    "manufacturer": "MediaTek",
    "performanceScore": 26,
    "performanceGrade": "C",
    "antutuScore": 268440,
    "geekbenchSingle": 441,
    "geekbenchMulti": 1407,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Mali-G52 MP2"
  },
  {
    "name": "Helio G81",
    "manufacturer": "MediaTek",
    "performanceScore": 26,
    "performanceGrade": "C",
    "antutuScore": 260675,
    "geekbenchSingle": 420,
    "geekbenchMulti": 1391,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Mali-G52 MP2"
  },
  {
    "name": "Helio G91",
    "manufacturer": "MediaTek",
    "performanceScore": 26,
    "performanceGrade": "C",
    "antutuScore": 274560,
    "geekbenchSingle": 405,
    "geekbenchMulti": 1407,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Mali-G52 MP2"
  },
  {
    "name": "Tiger T618",
    "manufacturer": "Unisoc",
    "performanceScore": 26,
    "performanceGrade": "C",
    "antutuScore": 281958,
    "geekbenchSingle": 469,
    "geekbenchMulti": 1456,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Mali-G52 MP2"
  },
  {
    "name": "Apple A9",
    "manufacturer": "Apple",
    "performanceScore": 26,
    "performanceGrade": "C",
    "antutuScore": 332764,
    "geekbenchSingle": 619,
    "geekbenchMulti": 953,
    "cores": 2,
    "coreConfig": "2",
    "clockSpeed": 1850,
    "gpu": "PowerVR GT7600"
  },
  {
    "name": "Snapdragon 670",
    "manufacturer": "Qualcomm",
    "performanceScore": 26,
    "performanceGrade": "C",
    "antutuScore": 250172,
    "geekbenchSingle": 381,
    "geekbenchMulti": 1239,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Adreno 615"
  },
  {
    "name": "Helio P90",
    "manufacturer": "MediaTek",
    "performanceScore": 26,
    "performanceGrade": "C",
    "antutuScore": 300868,
    "geekbenchSingle": 414,
    "geekbenchMulti": 1373,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2200,
    "gpu": "PowerVR GM9446"
  },
  {
    "name": "Tiger T615",
    "manufacturer": "Unisoc",
    "performanceScore": 25,
    "performanceGrade": "C",
    "antutuScore": 258142,
    "geekbenchSingle": 441,
    "geekbenchMulti": 1454,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 1800,
    "gpu": "Mali-G57 MP1"
  },
  {
    "name": "Tiger T612",
    "manufacturer": "Unisoc",
    "performanceScore": 25,
    "performanceGrade": "C",
    "antutuScore": 244837,
    "geekbenchSingle": 422,
    "geekbenchMulti": 1509,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 1800,
    "gpu": "Mali-G57 MP1"
  },
  {
    "name": "Tiger T616",
    "manufacturer": "Unisoc",
    "performanceScore": 25,
    "performanceGrade": "C",
    "antutuScore": 292658,
    "geekbenchSingle": 452,
    "geekbenchMulti": 1503,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Mali-G57 MP1"
  },
  {
    "name": "Helio G88",
    "manufacturer": "MediaTek",
    "performanceScore": 25,
    "performanceGrade": "C",
    "antutuScore": 268860,
    "geekbenchSingle": 425,
    "geekbenchMulti": 1355,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Mali-G52 MP2"
  },
  {
    "name": "Tiger T700",
    "manufacturer": "Unisoc",
    "performanceScore": 25,
    "performanceGrade": "C",
    "antutuScore": 260484,
    "geekbenchSingle": 429,
    "geekbenchMulti": 1434,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 1820,
    "gpu": "Mali-G52 MP2"
  },
  {
    "name": "Helio G85",
    "manufacturer": "MediaTek",
    "performanceScore": 25,
    "performanceGrade": "C",
    "antutuScore": 262684,
    "geekbenchSingle": 413,
    "geekbenchMulti": 1332,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Mali-G52 MP2"
  },
  {
    "name": "Snapdragon 662",
    "manufacturer": "Qualcomm",
    "performanceScore": 25,
    "performanceGrade": "C",
    "antutuScore": 247218,
    "geekbenchSingle": 339,
    "geekbenchMulti": 1208,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2000,
    "gpu": "Adreno 610"
  },
  {
    "name": "Helio G80",
    "manufacturer": "MediaTek",
    "performanceScore": 25,
    "performanceGrade": "C",
    "antutuScore": 247741,
    "geekbenchSingle": 416,
    "geekbenchMulti": 1354,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Mali-G52 MP2"
  },
  {
    "name": "Helio G70",
    "manufacturer": "MediaTek",
    "performanceScore": 25,
    "performanceGrade": "C",
    "antutuScore": 246700,
    "geekbenchSingle": 417,
    "geekbenchMulti": 1345,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Mali-G52 MP2"
  },
  {
    "name": "Snapdragon 665",
    "manufacturer": "Qualcomm",
    "performanceScore": 25,
    "performanceGrade": "C",
    "antutuScore": 235828,
    "geekbenchSingle": 335,
    "geekbenchMulti": 1166,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2000,
    "gpu": "Adreno 610"
  },
  {
    "name": "Unisoc T606",
    "manufacturer": "Unisoc",
    "performanceScore": 24,
    "performanceGrade": "D",
    "antutuScore": 246197,
    "geekbenchSingle": 371,
    "geekbenchMulti": 1391,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 1600,
    "gpu": "Mali-G57 MP1"
  },
  {
    "name": "Tiger T610",
    "manufacturer": "Unisoc",
    "performanceScore": 24,
    "performanceGrade": "D",
    "antutuScore": 250277,
    "geekbenchSingle": 418,
    "geekbenchMulti": 1305,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 1820,
    "gpu": "Mali-G52 MP2"
  },
  {
    "name": "Snapdragon 460",
    "manufacturer": "Qualcomm",
    "performanceScore": 24,
    "performanceGrade": "D",
    "antutuScore": 196586,
    "geekbenchSingle": 272,
    "geekbenchMulti": 992,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 1800,
    "gpu": "Adreno 610"
  },
  {
    "name": "Kirin 710F",
    "manufacturer": "HiSilicon",
    "performanceScore": 24,
    "performanceGrade": "D",
    "antutuScore": 251249,
    "geekbenchSingle": 352,
    "geekbenchMulti": 1244,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2200,
    "gpu": "Mali-G51 MP4"
  },
  {
    "name": "Helio P65",
    "manufacturer": "MediaTek",
    "performanceScore": 24,
    "performanceGrade": "D",
    "antutuScore": 212236,
    "geekbenchSingle": 375,
    "geekbenchMulti": 1186,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 2000,
    "gpu": "Mali-G52 MP2"
  },
  {
    "name": "Exynos 9611",
    "manufacturer": "Samsung",
    "performanceScore": 24,
    "performanceGrade": "D",
    "antutuScore": 257347,
    "geekbenchSingle": 370,
    "geekbenchMulti": 1103,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2300,
    "gpu": "Mali-G72 MP3"
  },
  {
    "name": "Kirin 710A",
    "manufacturer": "HiSilicon",
    "performanceScore": 23,
    "performanceGrade": "D",
    "antutuScore": 238420,
    "geekbenchSingle": 319,
    "geekbenchMulti": 1125,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2000,
    "gpu": "Mali-G51 MP4"
  },
  {
    "name": "Exynos 850",
    "manufacturer": "Samsung",
    "performanceScore": 23,
    "performanceGrade": "D",
    "antutuScore": 183771,
    "geekbenchSingle": 222,
    "geekbenchMulti": 868,
    "cores": 8,
    "coreConfig": "8",
    "clockSpeed": 2000,
    "gpu": "Mali-G52 MP1"
  },
  {
    "name": "Helio P70",
    "manufacturer": "MediaTek",
    "performanceScore": 23,
    "performanceGrade": "D",
    "antutuScore": 233983,
    "geekbenchSingle": 329,
    "geekbenchMulti": 1066,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2100,
    "gpu": "Mali-G72 MP3"
  },
  {
    "name": "Kirin 710",
    "manufacturer": "HiSilicon",
    "performanceScore": 23,
    "performanceGrade": "D",
    "antutuScore": 249206,
    "geekbenchSingle": 354,
    "geekbenchMulti": 1193,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2200,
    "gpu": "Mali-G51 MP4"
  },
  {
    "name": "Snapdragon 821",
    "manufacturer": "Qualcomm",
    "performanceScore": 23,
    "performanceGrade": "D",
    "antutuScore": 263454,
    "geekbenchSingle": 390,
    "geekbenchMulti": 792,
    "cores": 4,
    "coreConfig": "2+2",
    "clockSpeed": 2342,
    "gpu": "Adreno 530"
  },
  {
    "name": "Snapdragon 660",
    "manufacturer": "Qualcomm",
    "performanceScore": 23,
    "performanceGrade": "D",
    "antutuScore": 252006,
    "geekbenchSingle": 342,
    "geekbenchMulti": 1232,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2200,
    "gpu": "Adreno 512"
  },
  {
    "name": "Kirin 960",
    "manufacturer": "HiSilicon",
    "performanceScore": 23,
    "performanceGrade": "D",
    "antutuScore": 289944,
    "geekbenchSingle": 406,
    "geekbenchMulti": 1380,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2360,
    "gpu": "Mali-G71 MP8"
  },
  {
    "name": "Exynos 8890",
    "manufacturer": "Samsung",
    "performanceScore": 23,
    "performanceGrade": "D",
    "antutuScore": 299737,
    "geekbenchSingle": 321,
    "geekbenchMulti": 885,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2300,
    "gpu": "Mali-T880 MP12"
  },
  {
    "name": "Exynos 9610",
    "manufacturer": "Samsung",
    "performanceScore": 23,
    "performanceGrade": "D",
    "antutuScore": 261366,
    "geekbenchSingle": 373,
    "geekbenchMulti": 1042,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2300,
    "gpu": "Mali-G72 MP3"
  },
  {
    "name": "Helio G36",
    "manufacturer": "MediaTek",
    "performanceScore": 22,
    "performanceGrade": "D",
    "antutuScore": 142962,
    "geekbenchSingle": 229,
    "geekbenchMulti": 842,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2200,
    "gpu": "PowerVR GE8320"
  },
  {
    "name": "Helio G37",
    "manufacturer": "MediaTek",
    "performanceScore": 22,
    "performanceGrade": "D",
    "antutuScore": 156033,
    "geekbenchSingle": 205,
    "geekbenchMulti": 911,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2300,
    "gpu": "PowerVR GE8320"
  },
  {
    "name": "Helio G35",
    "manufacturer": "MediaTek",
    "performanceScore": 22,
    "performanceGrade": "D",
    "antutuScore": 144387,
    "geekbenchSingle": 189,
    "geekbenchMulti": 810,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2300,
    "gpu": "PowerVR GE8320"
  },
  {
    "name": "Helio P60",
    "manufacturer": "MediaTek",
    "performanceScore": 22,
    "performanceGrade": "D",
    "antutuScore": 186518,
    "geekbenchSingle": 299,
    "geekbenchMulti": 1155,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2000,
    "gpu": "Mali-G72 MP3"
  },
  {
    "name": "Helio P35",
    "manufacturer": "MediaTek",
    "performanceScore": 22,
    "performanceGrade": "D",
    "antutuScore": 149232,
    "geekbenchSingle": 260,
    "geekbenchMulti": 812,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2300,
    "gpu": "PowerVR GE8320"
  },
  {
    "name": "Helio G25",
    "manufacturer": "MediaTek",
    "performanceScore": 21,
    "performanceGrade": "D",
    "antutuScore": 125125,
    "geekbenchSingle": 185,
    "geekbenchMulti": 521,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 2000,
    "gpu": "PowerVR GE8320"
  },
  {
    "name": "Snapdragon 820",
    "manufacturer": "Qualcomm",
    "performanceScore": 21,
    "performanceGrade": "D",
    "antutuScore": 259958,
    "geekbenchSingle": 323,
    "geekbenchMulti": 821,
    "cores": 4,
    "coreConfig": "2+2",
    "clockSpeed": 2150,
    "gpu": "Adreno 530"
  },
  {
    "name": "Exynos 7904",
    "manufacturer": "Samsung",
    "performanceScore": 21,
    "performanceGrade": "D",
    "antutuScore": 190670,
    "geekbenchSingle": 286,
    "geekbenchMulti": 937,
    "cores": 8,
    "coreConfig": "2+6",
    "clockSpeed": 1800,
    "gpu": "Mali-G71 MP2"
  },
  {
    "name": "Snapdragon 636",
    "manufacturer": "Qualcomm",
    "performanceScore": 21,
    "performanceGrade": "D",
    "antutuScore": 218146,
    "geekbenchSingle": 294,
    "geekbenchMulti": 1083,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 1800,
    "gpu": "Adreno 509"
  },
  {
    "name": "Snapdragon 632",
    "manufacturer": "Qualcomm",
    "performanceScore": 21,
    "performanceGrade": "D",
    "antutuScore": 183418,
    "geekbenchSingle": 295,
    "geekbenchMulti": 1037,
    "cores": 8,
    "coreConfig": "4+4",
    "clockSpeed": 1800,
    "gpu": "Adreno 506"
  }
];
